name: exambeing
description: A new Flutter project for competitive exams.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  provider: ^6.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  collection: ^1.18.0

  # UI & Media Packages
  percent_indicator: ^4.2.3
  pinput: ^4.0.0
  google_fonts: ^5.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2

  # Firebase Packages
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

  # Local Database
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
