name: Migrate Old Code

on:
  workflow_dispatch: # Allows manual run

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission to save changes
    steps:
      # Step 1: Nayi repository (exambeing-final) ko checkout karein
      - name: Checkout new repository
        uses: actions/checkout@v4
        with:
          repository: opkukna1/exambeing-final
          path: main_repo

      # Step 2: Purani repository (exambeing) ko ek alag folder mein checkout karein
      - name: Checkout old repository
        uses: actions/checkout@v4
        with:
          repository: opkukna1/exambeing
          path: old_code

      # Step 3: Files ko transfer karein
      - name: Transfer lib and assets folders
        run: |
          cd main_repo
          # Naye project ka default lib folder delete karein
          rm -rf lib
          # Purane project se lib folder copy karein
          cp -r ../old_code/lib .
          # Purane project se assets folder copy karein (agar hai toh)
          if [ -d "../old_code/assets" ]; then
            cp -r ../old_code/assets .
          fi
      
      # Step 4: Nayi files ko naye repository mein save (commit) karein
      - name: Commit migrated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Migrate lib and assets from old repository"
          branch: main
          repository: main_repo
