name: Setup New Flutter Project

on:
  workflow_dispatch: # Allows manual run

jobs:
  create_project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Create a new Flutter project in the repo
        run: flutter create --org com.example --project-name exambeing .

      - name: Commit new Flutter project
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Create a new, clean Flutter project"
          branch: main
